import test from 'node:test';
import assert from 'node:assert/strict';
import {GameRuntime,SAVE_KEY} from './runtime.js';
import {validateContent} from './contracts.js';
import {GenerationQueue} from './generation.js';
const storage=()=>{const m=new Map();return{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)}};
function setup(store=storage()){let n=0;const game=new GameRuntime({storage:store,id:()=>`event-${++n}`,clock:()=>1000+n});return game}
function discover(g){for(const room of ['inn','smith','home'])g.record('room_entered',room,`Visited ${room}`)}
function offer(g,job){return{name:'Test wings',description:'A test-only attachment.',reason:'Based on recorded exploration.',tradeoff:'Replaces the current awakening.',sourceEventIds:job.eventIds,appearance:[{x:-20,y:-12,w:8,h:3,color:'#ddbb88'}],skill:{name:'Test pulse',description:'An animated pulse.',durationMs:600,cooldownMs:2000,effects:[{shape:'ring',color:'#ddbb88',radius:30,count:12,rotation:1}]}}}
function quest(g,job){return{title:'Test task',description:'Visit the inn.',sourceEventIds:job.eventIds,objectives:[{type:'visit_room',target:'inn',description:'Enter the inn'}]}}
test('three distinct discoveries queue one awakening; repeats do not farm evidence',()=>{const g=setup();discover(g);for(let i=0;i<5;i++)g.record('room_entered','inn','Visited inn');assert.equal(g.state.jobs.length,1);assert.equal(g.state.events.filter(e=>e.meaningful).length,3);assert.equal(g.state.activeAwakening,null)});
test('generated offers do not apply without acceptance; decline preserves active appearance',()=>{const g=setup();discover(g);const j=g.state.jobs[0];g.complete(j.id,offer(g,j));assert.equal(g.activeOffer(),undefined);g.decideAwakening(j.id,true);assert.equal(g.activeOffer().id,j.id);const second={...j,id:'second',status:'queued'};g.state.jobs.push(second);g.complete(second.id,offer(g,second));g.decideAwakening(second.id,false);assert.equal(g.activeOffer().id,j.id);g.complete(j.id,offer(g,j));assert.equal(g.state.offers.length,2)});
test('accepted content and factual journal survive reload',()=>{const store=storage(),g=setup(store);discover(g);const j=g.state.jobs[0];g.complete(j.id,offer(g,j));g.decideAwakening(j.id,true);const restored=setup(store);assert.equal(restored.activeOffer().content.name,'Test wings');assert.equal(restored.state.journal.length,4)});
test('quest requests deduplicate; only post-acceptance objectives complete',()=>{const g=setup();g.requestQuest();g.requestQuest();assert.equal(g.state.jobs.length,1);const j=g.state.jobs[0];g.complete(j.id,quest(g,j));g.record('room_entered','inn','Visited inn');assert.equal(g.state.quests[0].status,'offered');g.acceptQuest(j.id);g.record('room_entered','inn','Revisited inn');assert.equal(g.state.quests[0].status,'complete');g.record('room_entered','inn','Revisited inn');assert.equal(g.state.events.filter(e=>e.type==='quest_completed').length,1)});
test('contracts reject executable extras, bad references and impossible quests',()=>{const g=setup();discover(g);const j=g.state.jobs[0],a=offer(g,j),events=g.context(j).events;assert.throws(()=>validateContent('awakening',{...a,code:'alert(1)'},events));assert.throws(()=>validateContent('awakening',{...a,sourceEventIds:['invented']},events));assert.throws(()=>validateContent('quest',{...quest(g,j),objectives:[{type:'visit_room',target:'Cleave',description:'wrong'}]},events));assert.throws(()=>validateContent('awakening',{...a,appearance:[{x:100,y:0,w:1,h:1,color:'#ffffff'}]},events))});
test('content is validated on restore; interrupted jobs become retryable failures',()=>{const store=storage(),g=setup(store);discover(g);const j=g.state.jobs[0];g.complete(j.id,offer(g,j));g.decideAwakening(j.id,true);g.state.offers[0].content.appearance[0].x=999;g.state.jobs[0].status='running';g.changed();const restored=setup(store);assert.equal(restored.activeOffer(),undefined);assert.equal(restored.state.jobs[0].status,'failed')});
test('unconfigured provider never sends generation requests',async()=>{const g=setup();discover(g);const calls=[];const q=new GenerationQueue(g,{fetcher:async(url)=>{calls.push(url);return{ok:true,json:async()=>({configured:false})}}});await q.connect();assert.deepEqual(calls,['/api/generation/status']);assert.equal(g.state.jobs[0].status,'queued')});
test('failed requests remain available for explicit retry',async()=>{const g=setup();discover(g);const q=new GenerationQueue(g,{fetcher:async()=>({ok:false,json:async()=>({error:'Unavailable'})})});q.enabled=true;await q.pump();assert.equal(g.state.jobs[0].status,'failed');assert.equal(g.state.offers.length,0);assert.equal(g.state.jobs[0].error,'Unavailable')});
test('a slow response only uses its captured evidence',()=>{const g=setup();discover(g);const j=g.state.jobs[0];g.record('combo_learned','Cleave','Learned Cinder Cleave');assert.equal(g.context(j).events.length,3);const a=offer(g,j);a.sourceEventIds=[g.state.events.at(-1).id];assert.throws(()=>g.complete(j.id,a))});
