import test from 'node:test';
import assert from 'node:assert/strict';
import {validateContent} from './contracts.js';
import {formMove,partPose,formClip} from './form-renderer.js';
import {drawHero} from '../volcanic.js';
import {DEFAULT_CHARACTER} from '../content/characters.js';
import {GameRuntime} from './runtime.js';
const clip=()=>({durationMs:600,frames:[{at:0,poses:[]},{at:50,poses:[{part:'fin',x:6,y:2,angle:40}]},{at:100,poses:[]}]});
const form=()=>({species:'Floating ray',parts:['body','fin','eye','tail'].map(id=>({id,x:0,y:0,color:'#c45632',points:[{x:-4,y:0},{x:4,y:0},{x:0,y:-8}]})),idle:clip(),walk:clip(),dodge:clip(),...Object.fromEntries(['primary','heavy','special','guard'].map(name=>[name,{name,cooldownMs:1000,clip:clip()}]))});
test('custom forms persist and replace the human sprite completely',()=>{const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};const g=new GameRuntime({storage});g.finishCharacter({...DEFAULT_CHARACTER,form:form()});const restored=new GameRuntime({storage});assert.deepEqual(restored.state.profile.form,form());let polygons=0,humanPixels=0;const ctx=new Proxy({closePath:()=>polygons++,fillRect:()=>humanPixels++},{get:(o,k)=>o[k]||(()=>{})});drawHero(ctx,0,0,'#ffffff',1,'',false,{custom:restored.state.profile,kind:'Heavy',attack:.5});assert.equal(polygons,4);assert.equal(humanPixels,0)});
test('animation interpolation, action timing, and clip selection use generated data',()=>{const f=form();assert.deepEqual(partPose(f.walk,'fin',.25),{x:3,y:1,angle:20});assert.deepEqual(partPose(f.walk,'fin',1),{x:0,y:0,angle:0});assert.equal(formMove(f,'Heavy').duration,600);assert.equal(formMove(f,'Cleave').name,'heavy');assert.equal(formClip(f,{walking:true}),f.walk);assert.equal(formClip(f,{kind:'Bash',attack:.5}),f.guard.clip)});
test('invalid creature anatomy and motion cannot enter the engine',()=>{for(const mutate of [f=>f.parts[1].id='body',f=>f.walk.frames[1].poses[0].part='missing',f=>f.idle.frames[2].at=40,f=>f.primary.cooldownMs=599,f=>f.parts[0].script='alert(1)',f=>f.parts[0].points[0].x=900]){const f=form();mutate(f);assert.throws(()=>validateContent('creature',{name:'Ray',bio:'A floating ray.',form:f},[]))}});
