import {replaceContent} from './stable-content.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function installWorldUI({controller,simulation,canvas,player,redraw,sound=()=>{},showJournal=()=>{}}){
 const panel=document.createElement('details');panel.id='worldActions';panel.open=true;
 panel.innerHTML='<summary><span>✦ WHAT DO YOU DO?</span><small id="worldRequestState">Your words, your approach</small></summary><div class="world-action-content"><div id="worldStats"></div><div id="worldNearby"></div><div id="worldSelection"></div><div id="worldInventory"></div><form id="worldActionForm"><label for="worldIntent">Describe any action</label><div class="world-input-row"><textarea id="worldIntent" rows="2" maxlength="1200" placeholder="Distract Rowan, offer Clover a meal, or try something unexpected…"></textarea><button class="primary" type="submit">Act ↗</button></div></form><p id="worldMessage" role="status" aria-live="polite"></p><div class="world-action-footer"><span>Walking never waits for a reply.</span><button id="worldJournal" type="button">Journal</button><button id="worldReconnect" type="button">Reconnect</button></div></div>';
 document.body.append(panel);let selected=null;const input=panel.querySelector('textarea');
 function render(){const state=simulation.publicState(),entities=state.entities||[],position=player();const visible=entities.filter(e=>e.id!=='player'&&e.location.kind==='ground').map(entity=>({entity,distance:Math.hypot(entity.location.x-position.x,entity.location.y-position.y)})).sort((a,b)=>a.distance-b.distance).slice(0,7);
  const obligations=state.issues.filter(issue=>issue.actor==='player'&&issue.status==='open');
  replaceContent(panel.querySelector('#worldStats'),`<span>◆ ${state.player.coins} coins · Fatigue ${state.player.fatigue}</span>${obligations.map(issue=>`<button data-world-settle="${escape(issue.id)}">Settle supplies · ${issue.amount} coins</button>`).join('')}${state.player.evidence.length?`<details class="world-reputation"><summary>Your choices have left a mark</summary>${state.player.evidence.slice(-3).map(e=>`<p>${escape(e.text)}</p>`).join('')}</details>`:''}`);
  replaceContent(panel.querySelector('#worldNearby'),visible.length?'<span class="world-label">IN VIEW</span>'+visible.map(({entity})=>`<button type="button" data-world-select="${escape(entity.id)}" class="${selected===entity.id?'selected':''}">${escape(entity.name)}</button>`).join(''):'<span class="world-label">Explore to find something within reach.</span>');
  const inventory=entities.filter(e=>e.location.kind==='held'&&e.location.actor==='player');const entity=entities.find(e=>e.id===selected);const condition=state.actors.find(actor=>actor.id===selected);const clues=state.player.memories.filter(memory=>memory.kind==='discovery'&&memory.subject===selected);const held=entity?.location.kind==='held'&&entity.location.actor==='player';const reach=held?0:entity?.location.kind==='ground'?Math.hypot(entity.location.x-position.x,entity.location.y-position.y):Infinity;const interactRange=entity?.kind==='actor'?240:80;
  replaceContent(panel.querySelector('#worldSelection'),entity?`<div class="world-selected-copy"><b>${escape(entity.name)}</b><p>${escape(entity.description)}</p>${reach>interactRange?'<p class="world-range-hint">Walk closer to interact.</p>':''}${clues.map(clue=>`<blockquote>${escape(clue.text)}</blockquote>`).join('')}${condition?`<p>${escape(condition.mood)} · ${condition.wakefulness} · fatigue ${condition.fatigue}</p>`:''}</div><div class="world-context-buttons"><button data-world-direct="inspect" data-world-entity="${escape(entity.id)}" ${reach>110?'disabled data-out-of-reach="true"':''}>Examine</button><button data-world-direct="interact" data-world-entity="${escape(entity.id)}" ${reach>interactRange?'disabled data-out-of-reach="true"':''}>${entity.kind==='actor'?'Talk':held&&entity.props.food?'Eat':held&&entity.props.heal?'Use':entity.props.open!==undefined?(entity.props.open?'Close':'Open'):entity.props.mechanism?'Activate':held?'Use':'Pick up'}</button>${entity.kind==='actor'?inventory.map(item=>`<button data-world-give="${escape(item.id)}" data-world-recipient="${escape(entity.id)}" ${reach>80?'disabled data-out-of-reach="true"':''}>Give ${escape(item.name)}</button>`).join(''):''}${held?`<button data-world-direct="drop" data-world-entity="${escape(entity.id)}">Drop</button>`:''}</div>`:'<p class="world-select-hint">Click a person or object in the world to interact.</p>');
  replaceContent(panel.querySelector('#worldInventory'),inventory.length?'<span class="world-label">CARRYING</span>'+inventory.map(e=>`<button data-world-select="${escape(e.id)}">${escape(e.name)}</button>`).join(''):'');
  panel.querySelectorAll('[data-world-direct],[data-world-give],[data-world-settle]').forEach(button=>button.disabled=controller.playerPending||button.dataset.outOfReach==='true');
  panel.querySelector('button[type=submit]').disabled=controller.playerPending||!controller.enabled;
  panel.querySelector('#worldRequestState').textContent=controller.playerPending?'Considering your words…':controller.worker?'Someone is responding…':controller.enabled?'Your words, your approach':'Direct play · storyteller offline';
  panel.querySelector('#worldMessage').textContent=controller.status||'';
  panel.querySelector('#worldReconnect').hidden=controller.enabled&&!controller.failed.size;
 }
 panel.addEventListener('click',event=>{const select=event.target.closest('[data-world-select]');if(select){selected=select.dataset.worldSelect;render();redraw();}const settlement=event.target.closest('[data-world-settle]');if(settlement){controller.settle(settlement.dataset.worldSettle);render();redraw();}const give=event.target.closest('[data-world-give]');if(give){controller.give(give.dataset.worldGive,give.dataset.worldRecipient);render();redraw();}const action=event.target.closest('[data-world-direct]');if(action){sound('select');controller.direct(action.dataset.worldDirect,action.dataset.worldEntity);render();redraw();}});
 panel.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const words=input.value.trim();if(!words)return;const result=await controller.submit(words);if(result.ok&&input.value.trim()===words)input.value='';render();redraw();});
 input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();panel.querySelector('form').requestSubmit();}});
 panel.querySelector('#worldReconnect').onclick=()=>controller.connect();panel.querySelector('#worldJournal').onclick=showJournal;
 canvas.addEventListener('click',event=>{const bounds=canvas.getBoundingClientRect(),p=player(),scale=Math.max(bounds.width/800,bounds.height/600);const x=(event.clientX-bounds.left+(800*scale-bounds.width)*p.x/800)/scale,y=(event.clientY-bounds.top+(600*scale-bounds.height)*p.y/600)/scale;const targets=simulation.publicState().entities.filter(e=>e.id!=='player'&&e.location.kind==='ground').map(e=>({e,d:Math.hypot(e.location.x-x,e.location.y-y)})).sort((a,b)=>a.d-b.d);if(targets[0]?.d<32){selected=targets[0].e.id;panel.open=true;render();redraw();}});
 return{render,get selected(){return selected},focus(){panel.open=true;input.focus();},select(id){selected=id;panel.open=true;render();redraw();}};
}
const images=new Map();
const art={medicine:'bottle',ration:'apple',stone:'stone',crowbar:'crowbar','supply-chest':'chest','supply-note':'book','inn-chest':'chest','inn-note':'book','inn-ration':'apple'};
export function drawWorldObjects(context,state,selected){for(const entity of state.entities||[]){if(entity.kind==='actor'||entity.location.kind!=='ground')continue;const {x,y}=entity.location;const name=art[entity.id]||(entity.props.container?'chest':entity.props.food?'apple':null);context.save();context.translate(x,y);if(selected===entity.id){context.strokeStyle='#f1c57e';context.lineWidth=2;context.beginPath();context.ellipse(0,9,20,8,0,0,Math.PI*2);context.stroke();}if(name){if(!images.has(name)){const image=new Image();image.src=`/art/objects/${name}.png`;images.set(name,image)}const image=images.get(name);if(image.complete&&image.naturalWidth)context.drawImage(image,-16,-22,32,32);else{context.fillStyle='#d2b675';context.fillRect(-7,-8,14,14)}}else{context.fillStyle='#b7a77d';context.fillRect(-7,-12,14,17)}if(entity.props.container&&entity.props.open){context.fillStyle='#aed4b0';context.fillRect(-13,-25,26,2)}context.restore();}}
